INSERT INTO employee (
    fname,
    lname,
    nname,
    birthday,
    gander,
    governorate,
    city,
    st_or_ar,
    home_no,
    floor,
    university,
    certificate,
    degree,
    _work,
    note,
    salary,
    username,
    password
) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);